apiVersion: apps/v1
kind: Deployment
metadata:
   name: temporal-worker
   labels:
      app: temporal-worker
spec:
   selector:
      matchLabels:
         app: temporal-worker
   replicas: 1
   template:
      metadata:
         annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/agent-inject-status: 'update'
            vault.hashicorp.com/role: 'temporal-worker'
            vault.hashicorp.com/agent-inject-secret-database-config.txt: 'internal/data/database/config'
            vault.hashicorp.com/agent-inject-template-database-config.txt: |
               {{- with secret "internal/data/database/config" -}}
               postgresql://{{ .Data.data.username }}:{{ .Data.data.password }}@localhost:5432/dbname
               {{- end }}
         labels:
            app: temporal-worker
      spec:
         serviceAccountName: temporal-worker
         containers:
            - name: temporal-worker
              image: eklhad/temporal-infra-worker:latest
              resources:
                limits:
                  cpu: "0.5"
                  memory: "512Mi"
                requests:
                  cpu: "0.2"
                  memory: "256Mi"